INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, amount_limit, withdrawal, deposit_guarantee, web_link) VALUES (1, '4Spar', 6.5, 10, 'Sweden', 'SEK', '0-3 år', '1000 - 50 000 kr', 'Inga - Obegränsade', 'Nej', '<a class="btn btn-success btn-small" href="http://www.4spar.se/">Mer info</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, amount_limit, withdrawal, deposit_guarantee, web_link) VALUES (2, 'Akelius', 3, 5, 'Sweden', 'SEK', '0-3 år', 'Max 50 000 kr', '2 per år', 'Nej', '<a class="btn btn-success btn-small" href="http://www.akeliusspar.se/">Mer info</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, amount_limit, withdrawal, deposit_guarantee, web_link) VALUES (3, 'Ikano Bank', 0.5, 2, 'Sweden', 'SEK', '0-5 år', 'Obegränsat', 'Inga - Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.ikanobank.se/">Mer info</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, amount_limit, withdrawal, deposit_guarantee, web_link) VALUES (4, 'Avanza Bank', 0, 1.9, 'Sweden', 'SEK', '0-2 år', '100 kr - ', 'Inga - Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.avanza.se/">Mer info</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, amount_limit, withdrawal, deposit_guarantee, web_link) VALUES (5, 'Swespar', 6, 10,'Sweden', 'SEK', '0-3 år', '1 - 50 000 kr', 'Inga - Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.swespar.se/">Mer info</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, amount_limit, withdrawal, deposit_guarantee, web_link) VALUES (6, '24 Money', 6.5, 10,'Sweden', 'SEK', '0-2 år', '10 000 - ', 'Inga - Obegränsat', 'Nej', '<a class="btn btn-success btn-small" href="http://24moneyspar.se/">Mer info</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, amount_limit, withdrawal, deposit_guarantee, web_link) VALUES (7, '24 Spar', 4.75, 7.95,'Sweden', 'SEK', '0-3 år', 'Obegränsat', '4 per år - Obegränsat', 'Nej', '<a class="btn btn-success btn-small" href="http://www.24spar.se/">Mer info</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, amount_limit, withdrawal, deposit_guarantee, web_link) VALUES (8, 'Marginalen bank', 1.5, 3.10,'Sweden', 'SEK', '0-7 år', '0 - 5 000 000 kr', 'Inga - Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="https://www.marginalen.se/">Mer info</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, amount_limit, withdrawal, deposit_guarantee, web_link) VALUES (9, 'BlueStep Finans', 1.1, 2.6,'Sweden', 'SEK', '0-7 år', '0 - 800 000 kr', 'Inga - Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.bluestep.se">Mer info</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, amount_limit, withdrawal, deposit_guarantee, web_link) VALUES (10, 'BIGBANK', 1.3, 2.65,'Sweden', 'SEK', '0-7 år', '10 000 - 1 000 000 kr', 'Inga', 'Ja', '<a class="btn btn-success btn-small" href="https://www.bigbank.se/">Mer info</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, amount_limit, withdrawal, deposit_guarantee, web_link) VALUES (11, 'OK Ekonomisk förening', 0.5, 1.5,'Sweden', 'SEK', 'Ingen', 'Obegränsat', 'Obegränsat', 'Nej', '<a class="btn btn-success btn-small" href="http://www.ok.se/vara-foreningar/ok-pitea/aterbaring-och-ranta/">Mer info</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, amount_limit, withdrawal, deposit_guarantee, web_link) VALUES (12, 'Hoistspar', 1.6, 2.5,'Sweden', 'SEK', '0-3 år', '0 - 1 000 000 kr', 'Inga - Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://hoistspar.se/">Mer info</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, amount_limit, withdrawal, deposit_guarantee, web_link) VALUES (13, 'Nordea', 0.75, 1.25,'Sweden', 'SEK', '0-2 år', '0 - 1 000 000 kr', 'Inga - Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://nordea.se/">Mer info</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, amount_limit, withdrawal, deposit_guarantee, web_link) VALUES (14, 'SBAB', 1.2, 1.4,'Sweden', 'SEK', 'Ingen', 'Obegränsat', 'Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://sbab.se/">Mer info</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, amount_limit, withdrawal, deposit_guarantee, web_link) VALUES (15, 'Swedbank', 0, 1.15,'Sweden', 'SEK', '0-5 år', 'Obegränsat', 'Inga - Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://swedbank.se/">Mer info</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, amount_limit, withdrawal, deposit_guarantee, web_link) VALUES (16, 'Handelsbanken', 0, 0.5,'Sweden', 'SEK', '0-10 år', 'Obegränsat', 'Inga - Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://handelsbanken.se/">Mer info</a>');



SEB
Nordnet


INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (7, '24 Spar', 4.75, 7.95,'Sweden', 'SEK', 'Vissa villkor', 'Oegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.ikano.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (8, 'Marginalen', 1, 2,'Sweden', 'SEK', 'Inga villkor', 'Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.swedbank.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (9, 'BlueStep Finans', 4, 6,'Sweden', 'SEK', 'Inga villkor', 'Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.marginalen.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (10, 'BIGBANK', 1, 1.5,'Sweden', 'SEK', 'Inga villkor', 'Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.nordea.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (11, 'OK Ekonomisk förening', 5, 10,'Sweden', 'SEK', 'Vissa villkor', 'Begränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.4spar.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (12, 'HostSpar', 2, 3,'Sweden', 'SEK', 'Vissa villkor', 'Oegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.ikano.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (13, 'Solidum', 1, 2,'Sweden', 'SEK', 'Inga villkor', 'Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.swedbank.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (14, 'Collector', 4, 6,'Sweden', 'SEK', 'Inga villkor', 'Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.marginalen.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (15, 'Svea Ekonomi', 1, 1.5,'Sweden', 'SEK', 'Inga villkor', 'Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.nordea.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (17, 'GCC Capital', 5, 10,'Sweden', 'SEK', 'Vissa villkor', 'Begränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.4spar.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (18, 'Klarna Sparkonto', 2, 3,'Sweden', 'SEK', 'Vissa villkor', 'Oegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.ikano.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (19, 'PayEx Spara', 1, 2,'Sweden', 'SEK', 'Inga villkor', 'Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.swedbank.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (20, 'TF Bank', 4, 6,'Sweden', 'SEK', 'Inga villkor', 'Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.marginalen.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (21, 'Resurs Bank', 1, 1.5,'Sweden', 'SEK', 'Inga villkor', 'Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.nordea.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (22, 'Santande Consumer Bank', 5, 10,'Sweden', 'SEK', 'Vissa villkor', 'Begränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.4spar.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (23, 'Anita Finans', 2, 3,'Sweden', 'SEK', 'Vissa villkor', 'Oegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.ikano.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (24, 'AK Spar', 1, 2,'Sweden', 'SEK', 'Inga villkor', 'Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.swedbank.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (25, 'GE Money Bank', 4, 6,'Sweden', 'SEK', 'Inga villkor', 'Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.marginalen.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (26, 'Remium', 1, 1.5,'Sweden', 'SEK', 'Inga villkor', 'Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.nordea.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (27, 'Landshypotek', 5, 10,'Sweden', 'SEK', 'Vissa villkor', 'Begränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.4spar.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (28, 'Bank Norwegian', 2, 3,'Sweden', 'SEK', 'Vissa villkor', 'Oegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.ikano.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (29, 'SevenDay', 1, 2,'Sweden', 'SEK', 'Inga villkor', 'Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.swedbank.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (30, 'Danske Bank', 4, 6,'Sweden', 'SEK', 'Inga villkor', 'Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.marginalen.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (31, 'Avida Finans', 1, 1.5,'Sweden', 'SEK', 'Inga villkor', 'Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.nordea.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (32, 'Ńordea', 5, 10,'Sweden', 'SEK', 'Vissa villkor', 'Begränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.4spar.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (33, 'Volvofinans Bank', 2, 3,'Sweden', 'SEK', 'Vissa villkor', 'Oegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.ikano.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (34, 'SBAB', 1, 2,'Sweden', 'SEK', 'Inga villkor', 'Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.swedbank.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (35, 'Lantmännen Finans', 4, 6,'Sweden', 'SEK', 'Inga villkor', 'Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.marginalen.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (36, 'Ancoria Insurance', 1, 1.5,'Sweden', 'SEK', 'Inga villkor', 'Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.nordea.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (37, 'Ekobanken', 5, 10,'Sweden', 'SEK', 'Vissa villkor', 'Begränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.4spar.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (38, 'KF Sparkassa', 2, 3,'Sweden', 'SEK', 'Vissa villkor', 'Oegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.ikano.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (39, 'Swedbank', 1, 2,'Sweden', 'SEK', 'Inga villkor', 'Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.swedbank.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (40, 'Forex Bank', 4, 6,'Sweden', 'SEK', 'Inga villkor', 'Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.marginalen.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (41, 'Handelsbanken', 1, 1.5,'Sweden', 'SEK', 'Inga villkor', 'Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.nordea.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (42, 'SkandiaBanken', 2, 3,'Sweden', 'SEK', 'Vissa villkor', 'Oegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.ikano.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (43, 'SEB', 1, 2,'Sweden', 'SEK', 'Inga villkor', 'Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.swedbank.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (44, 'Sparbanken Öresund', 4, 6,'Sweden', 'SEK', 'Inga villkor', 'Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.marginalen.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (45, 'Nordnet', 1, 1.5,'Sweden', 'SEK', 'Inga villkor', 'Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.nordea.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (46, 'ICA Banken', 2, 3,'Sweden', 'SEK', 'Vissa villkor', 'Oegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.ikano.se/">Ansök här</a>');
INSERT INTO rates (id, bank, min_rate, max_rate, country, currency, conditions, withdrawal, deposit_guarantee, web_link) VALUES (47, 'Riksgälden', 1, 2,'Sweden', 'SEK', 'Inga villkor', 'Obegränsat', 'Ja', '<a class="btn btn-success btn-small" href="http://www.swedbank.se/">Ansök här</a>');
